#!/bin/sh
unifdef -USCOPEDROUTING -D__FreeBSD_cc_version=$1 -DSCTP_EMBEDDED_V6_SCOPE -U_SCTP_NEEDS_CALLOUT_ -D__FreeBSD_version=$1 -D SCTP_KAME -D__FreeBSD__ -U__Panda__ -U__NetBSD__ -U__OpenBSD__ -U__APPLE__ -USCTP_APPLE_PANTHER -U__Windows__ -U__Userspace__ -U__Userspace_os_Linux  -U__Userspace_os_FreeBSD -U__Userspace_os_Darwin -U__Userspace_os_Windows -U_USER_SCTP_NEEDS_CALLOUT_ -UCALLBACK_API $2 > temp.file
#
unifdef -USCTP_HMAC_TEST -UHAVE_SCTP_PEELOFF_SOCKOPT -UNEW_STRUCT_ROUTE -U__APPLE__ -UNRND -UHAVE_NRL_INPCB -U__Windows__ temp.file > temp.file2
#
unifdef -UKERNEL -USCTP_PROCESS_LEVEL_LOCKS -USCTP_MVRF -UAPPLE_LION -U__APPLE__ temp.file2 > temp.file
#
unifdef -U__FreeBSD8__ -D__FreeBSD__ -USCTP_PER_SOCKET_LOCKING -DWITH_CONVERT_IP_OFF temp.file > temp.file2
#
unifdef -DSCTP_INCRS_DEFINED temp.file2 > export_freebsd/$2
rm -f temp.file temp.file2
./s9indent export_freebsd/$2
mv export_freebsd/$2.s9 export_freebsd/$2


