#!/bin/sh
unifdef -DHAVE_SCTP_AUTH $1 > temp.file2
unifdef -USCOPEDROUTING -D__FreeBSD_cc_version=700000 -USCTP_BASE_FREEBSD -U_SCTP_NEEDS_CALLOUT_ -D__FreeBSD_version=700000 -D SCTP_KAME -D__FreeBSD__ -U__NetBSD__ -U__OpenBSD__ -U__APPLE__ -USCTP_APPLE_PANTHER temp.file2 > temp.file
#
unifdef -UHAVE_SCTP_PEELOFF_SOCKOPT -UNEW_STRUCT_ROUTE -U__APPLE__ -UNRND -USCTP_APPLE_FINE_GRAINED_LOCKING -U__APPLE1__ -UHAVE_NRL_INPCB temp.file > temp.file2
#
unifdef -UKERNEL -U__APPLE__ temp.file2 > temp.file
#
unifdef -D__FreeBSD__ -DWITH_CONVERT_IP_OFF temp.file > temp.file2
#
unifdef -DSCTP_INCRS_DEFINED temp.file2 > export_freebsd/$1
rm -f temp.file temp.file2



