#!/bin/sh
if test $# -ne 2
then
echo error use $0 log timeskip
exit
fi
../FreeBSD/prtcwndlog -a $2 -r -g -l $1.recv > $1.rcv.txt
../FreeBSD/prtcwndlog -r -g -l $1.send | grep FLIGHT > $1.flight.txt
../FreeBSD/prtcwndlog -r -g -l $1.send | grep ARWND > $1.arwnd.txt
../FreeBSD/prtcwndlog -r -g -l $1.send | grep RWND | grep -v ARWND > $1.rwnd.txt
../FreeBSD/prtcwndlog -r -g -l $1.send | grep OUT_QUEUE > $1.outq.txt
../FreeBSD/cntcwndlog -r -l $1.send -i 500 -c1000 > $1.cnt.txt
gnuplot <<!
set output 'plotall.ps'
set terminal post landscape 'Times-Roman' 12
set terminal post color
set xlabel 'time'
set ylabel 'size'
set multiplot
set key outside Right title 'Legend' box 1
plot '$1.flight.txt' title 'snd-flt', \
'$1.cnt.txt' title 'sack-cnt'

