#!/bin/sh
if test $# -ne 2
then
echo error use $0 log timeskip
exit
fi
../FreeBSD/prtcwndlog -r -g -l $1.recv -a "$2" | grep ENTER > $1.rcv.enter.txt
../FreeBSD/prtcwndlog -r -g -l $1.recv -a "$2" | grep EXIT > $1.rcv.exit.txt
../FreeBSD/prtcwndlog -r -g -l $1.send | grep FLIGHT > $1.flight.txt
../FreeBSD/prtcwndlog -r -g -l $1.send | grep ARWND > $1.arwnd.txt
../FreeBSD/prtcwndlog -r -g -l $1.send | grep RWND | grep -v ARWND > $1.rwnd.txt
gnuplot <<!
set output 'plotall.ps'
set terminal post landscape 'Times-Roman' 12
set terminal post color
set xlabel 'time'
set ylabel 'size'
set multiplot
set key outside Right title 'Legend' box 1
plot '$1.rcv.enter.txt' title 'ent-r', \
'$1.rcv.exit.txt' title 'ext-r', \
'$1.flight.txt' title 'snd-flt', \
'$1.rwnd.txt' title 'snd-arw', \
'$1.arwnd.txt' title 'snd-rwd'
unset multiplot
clear
reset
set output 'plot000-005.ps'
set terminal post landscape 'Times-Roman' 12
set terminal post color
set xlabel 'time'
set ylabel 'size'
set multiplot
set key outside Right title 'Legend' box 1
set xrange [.000:.005]
plot '$1.rcv.enter.txt' title 'ent-r', \
'$1.rcv.exit.txt' title 'ext-r', \
'$1.flight.txt' title 'snd-flt', \
'$1.rwnd.txt' title 'snd-arw', \
'$1.arwnd.txt' title 'snd-rwd'
unset multiplot
clear
reset
set output 'plot005-010.ps'
set terminal post landscape 'Times-Roman' 12
set terminal post color
set xlabel 'time'
set ylabel 'size'
set multiplot
set key outside Right title 'Legend' box 1
set xrange [.005:.010]
plot '$1.rcv.enter.txt' title 'ent-r', \
'$1.rcv.exit.txt' title 'ext-r', \
'$1.flight.txt' title 'snd-flt', \
'$1.rwnd.txt' title 'snd-arw', \
'$1.arwnd.txt' title 'snd-rwd'
unset multiplot
clear
reset
set output 'plot010-015.ps'
set terminal post landscape 'Times-Roman' 12
set terminal post color
set xlabel 'time'
set ylabel 'size'
set multiplot
set key outside Right title 'Legend' box 1
set xrange [.010:.015]
plot '$1.rcv.enter.txt' title 'ent-r', \
'$1.rcv.exit.txt' title 'ext-r', \
'$1.flight.txt' title 'snd-flt', \
'$1.rwnd.txt' title 'snd-arw', \
'$1.arwnd.txt' title 'snd-rwd'
unset multiplot
clear
reset
set output 'plot015-020.ps'
set terminal post landscape 'Times-Roman' 12
set terminal post color
set xlabel 'time'
set ylabel 'size'
set multiplot
set key outside Right title 'Legend' box 1
set xrange [.015:.020]
plot '$1.rcv.enter.txt' title 'ent-r', \
'$1.rcv.exit.txt' title 'ext-r', \
'$1.flight.txt' title 'snd-flt', \
'$1.rwnd.txt' title 'snd-arw', \
'$1.arwnd.txt' title 'snd-rwd'
unset multiplot
clear
reset
set output 'plot020-025.ps'
set terminal post landscape 'Times-Roman' 12
set terminal post color
set xlabel 'time'
set ylabel 'size'
set multiplot
set key outside Right title 'Legend' box 1
set xrange [.020:.025]
plot '$1.rcv.enter.txt' title 'ent-r', \
'$1.rcv.exit.txt' title 'ext-r', \
'$1.flight.txt' title 'snd-flt', \
'$1.rwnd.txt' title 'snd-arw', \
'$1.arwnd.txt' title 'snd-rwd'
unset multiplot
clear
reset
set output 'plot025-030.ps'
set terminal post landscape 'Times-Roman' 12
set terminal post color
set xlabel 'time'
set ylabel 'size'
set multiplot
set key outside Right title 'Legend' box 1
set xrange [.025:.030]
plot '$1.rcv.enter.txt' title 'ent-r', \
'$1.rcv.exit.txt' title 'ext-r', \
'$1.flight.txt' title 'snd-flt', \
'$1.rwnd.txt' title 'snd-arw', \
'$1.arwnd.txt' title 'snd-rwd'



