#!/bin/sh
# bwclient builds and launches the bandwidth benchmark client according to the user specifications
# E.g. ./bwclient dest-ip dest-port k will build using SCTP kernel stack
# ./bwclient dest-ip dest-port u will build using SCTP __Userspace__ stack

if [ $# -ne 3 ];
then
    echo "Usage: $0 dest-ip dest-port mode(enter k for SCTP kernel stack and u for SCTP userpace stack"
    exit 1
fi

if  [ "$3" != "k"  -a  "$3" != "u" ]; 
then
    echo "For mode: enter k for SCTP kernel stack and u for SCTP userpace stack"
    exit 1
fi

make clean -f hmakefile

# Build application according to user specified parameters
if [ "$3" = "u" ];
then
    v1=`uname`
    v2="-D__Userspace_os_"
    v3="$v2$v1"
    v4=`uname -p | sed 's/386/486/'`
if [ "$v1" = "FreeBSD" ];
then
    make BUILD=bclient CFLAGS="-g -U__FreeBSD__ -U__APPLE__ -U__Panda__ -U__Windows__ -D__Userspace__ $v3 -DUSERMODE -Wall -march=$v4" CPPFLAGS="-I.  -I./user_include" LDFLAGS="-L./user_lib -L." LIBS="-lumem -luserspace -lcrypto  -lpthread #-latomic_ops" -f hmakefile
else
    make BUILD=bclient CFLAGS="-g -U__FreeBSD__ -U__APPLE__ -U__Panda__ -U__Windows__ -D__Userspace__ $v3 -DUSERMODE -Wall" CPPFLAGS="-I.  -I./user_include" LDFLAGS="-L./user_lib -L." LIBS="-lumem -luserspace -lcrypto  -lpthread #-latomic_ops" -f hmakefile
fi
else
    make BUILD=bclient CFLAGS="-g  -UUSERMODE  -Wall" CPPFLAGS="-I/usr/include" LDFLAGS="" LIBS="-lsctp" -f hmakefile
fi


# Launch application with appropriate parameters
echo "\n\n./osubw_sctpclient $1 $2"
./osubw_sctpclient $1 $2


