#!/bin/bash
#
# this script shuts down any SCTP which is already on the system
#
# $1: The full path to the installation package.
# $2: The full path to the installation destination.
# $3: The mountpoint of the destination volume.
# $4: The root directory for the current System folder.
#
# (c) Copyright 2006/2007 Andreas Fink <andreas@fink.org>

/Library/StartupItems/SCTP/SCTP stop
