MANOWN:=rrs
MANGRP:=rrs
MANDIR=/usr/local/man/man

MAN+=sctp.4 sctp_bindx.3 sctp_connectx.3 sctp_freepaddrs.3 \
sctp_getaddrlen.3 sctp_getassocid.3 sctp_getpaddrs.3 \
sctp_opt_info.3 sctp_recvmsg.3 sctp_send.3 sctp_sendmsg.3 \
sctp_generic_recvmsg.2 sctp_generic_sendmsg.2 sctp_peeloff.2 

MLINKS+= sctp_send.3 sctp_sendx.3
MLINKS+= sctp_sendmsg.3 sctp_sendmsgx.3
MLINKS+= sctp_freepaddrs.3 sctp_freeladdrs.3
MLINKS+= sctp_getpaddrs.3 sctp_getladdrs.3

.include <bsd.prog.mk>


