all:
	@cd ft_001_pingpong; ${MAKE}
	@cd ut_001_invalidarg; ${MAKE}
	@cd ut_002_setopt; ${MAKE}
	@cd ut_003_bind; ${MAKE}
	@cd ut_004_connect; ${MAKE}
	@cd ut_005_sctp_bindx; ${MAKE}
	@cd ut_006_sctp_sendmsg; ${MAKE}
	@cd ut_007_sctp_sockopts; ${MAKE}

clean:
	@cd ft_001_pingpong; ${MAKE} clean
	@cd ut_001_invalidarg; ${MAKE} clean
	@cd ut_002_setopt; ${MAKE} clean
	@cd ut_003_bind; ${MAKE} clean
	@cd ut_004_connect; ${MAKE} clean
	@cd ut_005_sctp_bindx; ${MAKE} clean
	@cd ut_006_sctp_sendmsg; ${MAKE} clean
	@cd ut_007_sctp_sockopts; ${MAKE} clean

