int sctp_socketpair(int *);
int sctp_shutdown(int);
int sctp_abort(int);
int sctp_enable_non_blocking(int);
int sctp_disable_non_blocking_blocking(int);
int sctp_set_rto_info(int, sctp_assoc_t, uint32_t, uint32_t, uint32_t);
int sctp_set_initial_rto(int , sctp_assoc_t, uint32_t);
int sctp_set_maximum_rto(int , sctp_assoc_t, uint32_t);
int sctp_set_minimum_rto(int , sctp_assoc_t, uint32_t);
int sctp_get_rto_info(int, sctp_assoc_t, uint32_t *, uint32_t *, uint32_t *);
int sctp_get_initial_rto(int fd, sctp_assoc_t, uint32_t *);
int sctp_get_maximum_rto(int fd, sctp_assoc_t, uint32_t *);
int sctp_get_minimum_rto(int fd, sctp_assoc_t, uint32_t *);
